import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

/**
 * Generated class for the SearchPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-search',
  templateUrl: 'search.html',
})
export class SearchPage {
  items;
  
  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

// ใส่คำศัพท์
initializeItems() {
  this.items = [
    'abide by (v.) ยอมปฏิบัติตาม ',
    'accidental (adj.) โดยบังเอิญ ',
    'accomodate (v.) จัดให้เหมาะสม ',
    'accuracy (n.) ความแม่นยํา ',
    'activate (V.) กระตุ้น ',
    'additional (adj.) ที่เพิ่มขึ้นมา, ส่วนเพิ่มเติม ',
    'advance (V.) พัฒนา',
    'advanced (adj.) ก้าวหน้า, สูง ',
    'advantageous (adj.) มีประโยชน์ให้คุณ ',
    'adviser (n.) ที่ปรึกษา',
    'affect (v.) กระทบ',
    'affordable (adj.) ที่สามารถจ่ายได้ ',
    'aisle (n.) ทางเดิน, ระหว่างที่นั่ง ',
    'allocate (V.) แบ่ง, จัดสรร',
    'allocate (v.) จัดสรร (หน้าที่, เงิน) ',
    'alter (V.) ปรับเปลี่ยน',
    'amateur (n.) มือสมัครเล่น',
    'analyst (n.) นักวิเคราะห์',
    'announcement (n.) ประกาศ',
    'annual (adj.) ประจํา, รายปี ',
    'apologize (v.) ขอโทษ ',
    'apology (n.) คำขอโทษ ',
    'applaud (v.) ปรบมือ',
    'appliance (n.) เครื่องใช้',
    'applicable (adj.) ใช้ได้, เหมาะสม',
    'application (n.) ใบสมัครงาน',
    'approve (V.) อนุมัติ, เห็นชอบ ',
    'approximate (adj.) ราวๆ ประมาณ',
    'arrival (n.) การมาถึง',
    'arrive (v.) มาถึง',
    'assemble (v.) ประกอบ, รวมตัวกัน',
    'assessment (n.) การประเมิน ',
    'assistant (n.) ผู้ช่วย',
    'associate (v.) มีความสัมพันธ์',
    'association (n.) องค์กร, สมาคม ',
    'assume (V.) สันนิษฐาน ',
    'assurance (n.) การรับประกัน, ความเชื่อมั่น ',
    'assure (V.) ทําให้เชื่อมั่น',
    'atmosphere (n.) บรรยากาศ',
    'attract (V.) ดึงดูด, ทําให้สนใจ ',
    'attribute (n.) คุณภาพ, คุณสมบัติ ',
    'auction (n.) การประมูล ',
    'audience (n.) ผู้ชม',
    'Philadelphia',
    'audit (n.) การตรวจสอบบัญชี',
    'auditorium (n.) หอประชุม',
    'aware (adj.) ที่ตระหนักรู้ ',
    'baggage (n.) สัมภาระ ',
    'balance (n.) ยอดคงเหลือ',
    'banquet (n.) งานเลี้ยงรื่นเริง ',
    'bargain (V.) ต่อรอง, เจรจา ',
    'benefit (n.) ผลประโยชน์ ',
    'beverage (n.) เครื่องดื่ม ',
    'board (v.) ขึ้น (ยานพาหนะ)',
    'break down (v.) เสีย, พัง, ไม่ทํางาน ',
    'calculate (v.) คํานวณ',
    'cancellation (n.) การยกเลิก ',
    'candidate (n.) ผู้สมัคร, ผู้เข้าแข่งขัน ',
    'capacity (n.) ความจุ, ความสามารถ ',
    'career (n.) อาชีพ',
    'casually (adv.) อย่างไม่เป็นทางการ ',
    'characteristic of (adj.) เป็นลักษณะพิเศษของ',
    'charity (n.) การกุศล',
    'client (n.) ลูกค้า, ผู้ซื้อ ',
    'collaborate (v.) ร่วมมือ ',
    'collaborative (adj.) ที่ร่วมมือกัน (หลายฝ่าย) ',
    'commercial (n.) โฆษณาทางโทรทัศน์, วิทยุ ',
    'commit (V.) สัญญา, ผูกมัด ',
    'committee (n.) คณะกรรมการ ',
    'compare (v.) เปรียบเทียบ',
    'compatible (adj.) ที่ทํางานร่วมกันได้ ',
    'compensation (n.) การชดเชย, ค่าตอบแทน ',
    'complaint (n.) ขอรองเรียน ',
    'complimentary (adj.) ให้ฟรี',
    'comply (V.) เชื่อฟัง, ยอมทําตาม ',
    'compromise (V.) ประณีประนอม',
    'concerned (adj.) กังวล',
    'conclude (v.) สรุป, หยุด, จบ',
    'Philadelphia',
    'conduct (v.) จัดการ, ควบคุม ',
    'confidential (adj.) เป็นความลับ',
    'consequence (n.) ผลลัพธ์, ผลที่ตามมา ',
    'consider (V.) พิจารณา ',
    'considerably (adv.) อย่างมาก ',
    'construction (n.) การก่อสร้าง ',
    'consume (V.) บริโภค, ใช้หมดไป, สูญสิ้นไป ',
    'convenient (adj.) สะดวก, สบาย ',
    'convince (V.) โน้มน้าว',
    'correspondence (n.) จดหมายขาว',
    'cost (n.) ราคา ต้นทุน ',
    'courteous (adj.) สุภาพนอบน้อม ',
    'currency (n.) เงินตรา',
    'current (adj.) เป็นปัจจุบัน, ณ เวลานี้ ',
    'customize (V.) ปรับตามความต้องการ ',
    'debt (n.) หนี้สิน',
    'declare (v.) ประกาศ. แถลง, แจ้ง ',
    'deduct (v.) หักออก',
    'defect (n.) ตําหนิ, ข้อบกพร่อง ',
    'deficit (n.) การขาดดุล',
    'delegate (v.) มอบหมายให้ทําแทน',
    'demonstrate (V.) สาธิต, แสดงให้เห็น ',
    'departure (n.) ลาออก',
    'dependable (adj.) พึ่งพาได้, ไว้ใจได้ ',
    'deposit (V.) ฝากเงิน',
    'describe (v.) บรรยาย, อธิบาย ',
    'deserve (V.) สมควรได้รับ ',
    'destination (n.) จุดหมายปลายทาง',
    'determine (v.) ตัดสินใจ, กําหนดระบุ ',
    'directory (n.) สมุดโทรศัพท์ ',
    'discount (n.) สวนลด',
    'discuss (v.) สนทนา, ถกปัญหา ',
    'discussion (n.) การอภิปรายแลกเปลี่ยนความ ',
    'distinct (adj.) แตกต่าง, ชัดเจน ',
    'distribute (v.) แจกจ่าย, กระจาย',
    'donation (n.) การบริจาค',
    'downturn (n.) ขาวง, แนวโน้มที่แย่ลง',
    'drastically (adv.) อย่างรวดเร็ว',
    'duplicate (v.) ทําสําเนา ',
    'durable (adj.) คงทน, มั่นคง',
    'effective (adj.) มีประสิทธิภาพ ',
    'eligible (adj.) มีคุณสมบัติเหมาะสม ',
    'enthusiastic (adj.) กระตือรือร้น',
    'envelope (n.) ซองจดหมาย',
    'establish (v.) จัดตั้ง, ก่อตั้ง ',
    'estimate (V.) ประมาณ',
    'evaluate (V.) ประเมิน',
    'evaluation (n.) การประเมิน',
    'exclude (v.) ไม่รวม, แยกออก ',
    'expand (V.) ขยาย, เพิ่มมากขึ้น ',
    'expert (n.) ผู้เชี่ยวชาญ ',
    'expiration date (n.) วันหมดอายุ ',
    'facilitate (v.) ทําให้ง่ายขึ้น, สะดวกขึ้น ',
    'figure out (V.) คํานวณแก้ปัญหา ',
    'flaw (n.) ตําหนิ, ข้อบกพร่อง',
    'fluent (adj.) คลองแคล่ว',
    'forecast (v.) คาดการณ์ล่วงหน้า',
    'frank (adj.) ตรงไปตรงมา, ไม่อ้อมค้อม ',
    'fraud (n.) การฉ้อโกง',
    'fulfill (V.) เติมเต็ม, ทําให้สําเร็จ ',
    'gather (V.) รวบรวม ',
    'generate (v.) ผลิต, ก่อให้เกิด',
    'grocery (n.) ร้านขายของชํา ',
    'headquarters (n.) สํานักงานใหญ่ ',
    'hire (V.) จ้างงาน',
    'impartial (adj.) เป็นกลาง, ยุติธรรม',
    'implement (V.) เริ่มนําไปใช้',
    'impress (v.) ทําให้ประทับใจ ',
    'incentive (n.) สิ่งจูงใจ ',
    'inclusive (adj.) ครอบคลุม, รวมทั้งหมด ',
    'income (n.) รายได้',
    'inflation (n.) ภาวะเงินเฟ้อ',
    'inform (V.) แจ้งให้ทราบ ',
    'inquiry (n.) การสอบถาม',
    'inspection (n.) การตรวจตรา ',
    'institute (n.) สถาบัน, องค์กร ',
    'instruction (n.) คําแนะนําการใช้งาน ',
    'interest (n.) ดอกเบี้ย, ผลประโยชน์ ',
    'interfere (V.) กาวกาย, รบกวน ',
    'inventory (n.) สินค้าคงคลัง ',
    'invest (V.) ลงทุน',
    'invoice (n.) ใบแจ้งราคาสินค้า',
    'itinerary (n.) กําหนดการเดินทาง',
    'lengthy (adj.) ยาวมาก, ยืดยาว ',
    'loan (n.) เงินกู้',
    'manner (n.) มารยาท, กิริยาท่าทาง ',
    'manufacturer (n.) ผู้ผลิต ',
    'merchandise (n.) สินค้า, ผลิตภัณฑ์',
    'minimize (v.) ทําให้ลดลง ',
    'necessity (n.) ความจําเป็น ',
    'obligate (v.) ผูกมัด, จําเป็นต้องทํา, ตามหน้าที่',
    'obtain (v.) ได้มา',
    'offer (n.) ขอเสนอ',
    'official (n.) เจ้าหน้าที่ ',
    'omit (V.) ละไว้, เว้นไว้ ',
    'opposition (adj.) ความขัดแย้ง ',
    'orientation (n.) ปฐมนิเทศ ',
    'outdated (adj.) ล้าสมัย ',
    'permit (V.) อนุญาต ',
    'personal (adj.) ส่วนบุคคล ',
    'policy (n.) นโยบาย, แผนการ ',
    'primarily (adv.) โดยส่วนมากแล้ว, ตั้งแต่แรก',
    'priority (n.) ลำดับความสําคัญ',
    'productive (adj.) ก่อให้เกิดผล, มีประสิทธิภาพ',
    'quotation (n.) ใบเสนอราคา ',
    'rapidly (adv.) อย่างรวดเร็ว',
    'recruit (V.) รับคน, จ้างพนักงาน ',
    'region (n.) ภูมิภาค ',
    'regulation (n.) กฎเกณฑ์, ข้อบังคับ ',
    'reimbursement (n.) การชําระเงินคืน ',
    'renovate (V.) ปรับปรุง, ซ่อมแซม ',
    'renowned (adj.) มีชื่อเสียง ',
    'reputation (n.) ชื่อเสียง',
    'resolve (v.) แก้ไขปัญหา ',
    'revenue (n.) รายได้ ',
    'salary (n.) เงินเดือน ',
    'satisfaction (n.) ความพึงพอใจ ',
    'satisfactory (adj.) น่าพอใจ',
    'short (adj.) ขาด ',
    'shrinking (n.) การหดตัว ',
    'soaring (adj.) เพิ่มขึ้นอย่างรวดเร็ว',
    'specific (adj.) เฉพาะเจาะจง',
    'strategically (adv.) อย่างมีกลยุทธ์ ',
    'strategy (n) กลยุทธ์',
    'substantial (adj.) มาก, สําคัญ ',
    'substitution (n.) การแทนที่ ',
    'sufficient (adj.) เพียงพอ ',
    'take over as (phrv.) เข้าทํางานต่อ, รับตําแหน่งต่อ',
    'task (n.) งาน, ภารกิจ ',
    'temporary (adj.) ชั่วคราว',
    'transaction (n.) รายการธุรกรรม',
    'unveil (v.) เปิดเผย ',
    'upcoming (adj.) กําลังมาถึง',
    'urgent (adj.) เร่งดวน ',
    'valid (adj.) มีเหตุผล. ถูกต้อง, ใช้ได้ ',
    'workforce (n.) แรงงาน, คนทํางาน'
  ];
}

getItems(ev) {
  // Reset items back to all of the items
  this.initializeItems();

  // set val to the value of the ev target
  var val = ev.target.value;

  // if the value is an empty string don't filter the items
  if (val && val.trim() != '') {
    this.items = this.items.filter((item) => {
      return (item.toLowerCase().indexOf(val.toLowerCase()) > -1);
    })
  }
}


  // คำสั่งต้องมี
  ionViewDidLoad() {
    console.log('ionViewDidLoad SearchPage');
  }
  gotoPage(search){
    this.navCtrl.push(search);
    }
}
